packages:
  - packages/**
  - app
    # exclude packages that are inside dist/build/.next
  - "!**/.next/**"
  - "!**/dist/**"
  - "!**/build/**"

catalogs:
  next:
    "next": 15.1.7
  effect:
    "effect": 3.13.4
    "@effect/platform-node": 0.73.2
    "@effect/platform": 0.77.4
  frontend:
    "@headlessui/react": 2.2.2
    radix-ui: 1.3.4
    "usehooks-ts": 3.1.1
    "@tanstack/react-query": 5.66.9
    "@tanstack/react-table": 8.16.0
    "@types/react-dom": 19.0.1
    "@types/react": 19.0.1
    "class-variance-authority": 0.7.0
    "cmdk": 1.0.0
    "date-fns-tz": 3.2.0
    "date-fns": 3.6.0
    "lucide-react": 0.435.0
    "nuqs": 2.4.1
    "react-dom": 19.0.0
    "react-hook-form": 7.54.2
    "react": 19.0.0
  backend:
    "@types/node-forge": 1.3.11
    "@types/node": 22.13.5
    "node-forge": 1.3.1
  test:
    "@playwright/experimental-ct-react": 1.45.3
    "@playwright/test": 1.45.3
    "msw": 2.7.3
    "vitest": 3.0.7
    "@vitest/coverage-istanbul": 3.0.7
    "@vitest/ui": 3.0.7
  lint:
    "@typescript-eslint/eslint-plugin": 8.25.0
    "@typescript-eslint/parser": 8.25.0
    "eslint-config-next": 15.1.7
    "eslint-config-prettier": 10.0.1
    "eslint-import-resolver-typescript": 3.8.3
    "eslint": 9.21.0
    "stylelint": "^16.14.1"
  types:
    "typescript": 5.8.2
    "ts-essentials": 10.0.4
    "@total-typescript/ts-reset": 0.6.1
    "@total-typescript/shoehorn": 0.1.2
    "tsafe": 1.8.5
  storybook:
    "storybook": "^8.6.4"
    "@storybook/addon-a11y": "^8.6.4"
    "@storybook/addon-essentials": "^8.6.4"
    "@storybook/addon-interactions": "^8.6.4"
    "@storybook/addon-links": "^8.6.4"
    "@storybook/addon-onboarding": "^8.6.4"
    "@storybook/addon-themes": "^8.6.4"
    "@storybook/blocks": "^8.6.4"
    "@storybook/manager-api": "^8.6.4"
    "@storybook/nextjs": "^8.6.4"
    "@storybook/react-vite": "^8.6.4"
    "@storybook/react": "^8.6.4"
    "@storybook/test": "^8.6.4"
    "@storybook/theming": "^8.6.4"
    "@storybook/addon-storysource": "^8.6.4"
  utils:
    "@types/lodash": 4.17.7
    "lodash": 4.17.21
    "jose": 5.8.0
    "openapi-fetch": 0.13.4
    "openapi-typescript": 7.6.1
    "zod": "^3.24.2"
  tools:
    "@t3-oss/env-nextjs": 0.12.0
    "@turbo/gen": "^2.4.4"
    "prettier": 3.5.2
    "jiti": 1.21.6
    "tsx": 4.19.3
  build:
    "@vitejs/plugin-react": 4.3.4
    "postcss-focus-visible": 10.0.0
    "postcss": 8.4.49
    "tailwindcss": 4.0.12
    "@tailwindcss/postcss": 4.0.12
    "vite": 6.2.0
