services:
  app:
    profiles:
      - all
      - app
    image: ${NODE_IMAGE}
    working_dir: ${APP_DIR}
    command: ["pnpm", "run", "dev"]
    env_file:
      - "./.env.application"
    volumes:
      - ../.:${APP_DIR}
      - $HOME/.npmrc:/.npmrc
    ports:
      - "3000:3000"
    user: "${CURRENT_UID}:${CURRENT_UID}"
    networks:
      - webapp
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=webapp"
      - "traefik.http.routers.${DOCKER_ID}-sandbox.rule=Host(`${APP_FQDN}`)"
      - "traefik.http.routers.${DOCKER_ID}-sandbox.entrypoints=https"
      - "traefik.http.routers.${DOCKER_ID}-sandbox.tls=true"
      - "traefik.http.routers.${DOCKER_ID}-sandbox.tls.certresolver=local"
      - "traefik.http.services.${DOCKER_ID}-sandbox.loadbalancer.server.port=3000"

networks:
  webapp:
    external: true
