import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "~/styles/globals.css";
import { NuqsAdapter } from "nuqs/adapters/next";
import { Toaster } from "@project/ui/components/toast";
import LayoutStructure from "./_layout/layout-structure";
import { Providers } from "~/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <LayoutStructure>{children}</LayoutStructure>
        </Providers>

        <Toaster />
      </body>
    </html>
  );
}
